[package]
name = "nydus-utils"
version = "0.1.0"
description = "Utilities for Nydus and Rafs"
authors = ["The Nydus Developers"]
repository = "https://github.com/dragonflyoss/image-service"
edition = "2018"

[dependencies]
log = "0.4.8"
lazy_static = "1.4"
libc = "0.2"
sha2 = "0.9.1"
blake3 = "0.3.6"
serde = { version = ">=1.0.27", features = ["serde_derive", "rc"] }
serde_json = ">=1.0.9"
fuse-backend-rs = { git = "https://github.com/cloud-hypervisor/fuse-backend-rs.git", optional = true, rev = "cfd2cca", package = "fuse-rs" }

# used by fuse.rs, should be moved into fuse-backend-rs
nix = "0.17"
epoll = "4.0"
vmm-sys-util = "0.6"

nydus-error = "0.1"

[features]
fusedev = ["fuse-backend-rs/fusedev"]
